---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/21/2023 6:06 PM
---

require "prototypes.boss-projectiles"
require "prototypes.projectiles"
require "prototypes.death"

require "prototypes.enemy.zealot"
require "prototypes.enemy.templar"
require "prototypes.enemy.shuttle"
require "prototypes.enemy.scout"
require "prototypes.enemy.scarab"
require "prototypes.enemy.reaver"
require "prototypes.enemy.probe"
require "prototypes.enemy.interceptor"
require "prototypes.enemy.dragoon"
require "prototypes.enemy.darktemplar"
require "prototypes.enemy.darkarchon"
require "prototypes.enemy.corsair"
require "prototypes.enemy.carrier"
require "prototypes.enemy.archon"
require "prototypes.enemy.arbiter"

require "prototypes.building.warpgate"
require "prototypes.building.templar_archive"
require "prototypes.building.stargate"
require "prototypes.building.shield_battery"
require "prototypes.building.robotics_support_bay"
require "prototypes.building.robotics_facility"
require "prototypes.building.pylon"
require "prototypes.building.nexus"
require "prototypes.building.gateway"
require "prototypes.building.forge"
require "prototypes.building.fleet_beacon"
require "prototypes.building.cybernetics_core"
require "prototypes.building.cannon"
require "prototypes.building.citadel_adun"
require "prototypes.building.arbiter_tribunal"