---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/21/2023 6:59 PM
---

require('__erm_toss__/global')
local ErmConfig = require('__enemyracemanager__/lib/global_config')
local AnimationDB = require('__erm_toss_hd_assets__/animation_db')

local create_psystorm_projectile = function(tier)
    local entity = data.raw['projectile'][MOD_NAME.."/psystorm-projectile-t"..tier]
    entity['animation'] = AnimationDB.get_layered_animations('projectiles','dragoon','projectile')
end

local create_stasis_projectile = function(tier)
    local entity = data.raw['projectile'][MOD_NAME.."/stasis-projectile-t"..tier]
    entity['animation'] = AnimationDB.get_layered_animations('projectiles','dragoon','projectile')
end

local create_cold_fire_projectile = function(tier)
    local entity = data.raw['projectile'][MOD_NAME.."/cold-fire-projectile-t"..tier]
    entity['animation'] = AnimationDB.get_layered_animations('projectiles','dragoon','projectile')
end

local create_cold_star_projectile = function(tier)
    local entity = data.raw['projectile'][MOD_NAME.."/cold-star-projectile-t"..tier]
    entity['animation'] = AnimationDB.get_layered_animations('projectiles','dragoon','projectile')
end

local create_recall_projectile = function(tier, script_attack)
    local entity = data.raw['projectile'][MOD_NAME.."/recall-"..script_attack.."-projectile-t"..tier]
    entity['animation'] = AnimationDB.get_layered_animations('projectiles','dragoon','projectile')
end


for i = 1, ErmConfig.BOSS_MAX_TIERS do
    create_psystorm_projectile(i)
    create_stasis_projectile(i)
    create_cold_fire_projectile(i)
    create_cold_star_projectile(i)
    create_recall_projectile(i, BOSS_SPAWN_ATTACK)
    create_recall_projectile(i, UNITS_SPAWN_ATTACK)
end