---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by heyqule.
--- DateTime: 7/23/2023 8:53 PM
---

local ERM_UnitTint = require('__enemyracemanager__/lib/rig/unit_tint')
require('__erm_toss__/global')
require('util')
local ErmConfig = require('__enemyracemanager__/lib/global_config')
local AnimationDB = require('__erm_toss_hd_assets__/animation_db')

local name = 'reaver'

--- Change collision box in case the scale not match
--- Changing collision box may affect unit pathing.. Be careful when you change it.
local collision_box = { { -0.25, -0.25 }, { 0.25, 0.25 } }
local selection_box = { { -1.5, -1.25 }, { 1.5, 1.25 } }

--- This function convert classic to HD graphic
--- i is the level of the unit.
local convert_to_hd = function(i)
    --- Get the data block
    local unit = data.raw["unit"][MOD_NAME..'/'.. name ..'/'.. i]

    --- Replace running animation
    unit['run_animation'] = AnimationDB.get_layered_animations('units', name, 'run')

    --- Replace attack animation
    unit['attack_parameters']['animation'] = AnimationDB.get_layered_animations('units', name, 'run')

    unit['collision_box'] = collision_box
    unit['selection_box'] = selection_box
    unit['sticker_box'] = selection_box

    unit['distance_per_frame'] = 0.16
end


--- Convert regular units, level 1 - 25
local max_level = ErmConfig.MAX_LEVELS

for i = 1, max_level + ErmConfig.MAX_ELITE_LEVELS do
    convert_to_hd(i)
end

--- Convert boss units
local boss_level = ErmConfig.BOSS_LEVELS

for i = 1, #boss_level do
    convert_to_hd(boss_level[i])
end
